import type { Endpoint, PayloadRequest } from 'payload'
import { APIError } from 'payload'

import { isAdminUser } from '../access'
import { revalidateForRaceSchedule } from '../lib/revalidate-public'

/**
 * The daily upkeep the race schedule needs, and nothing more.
 *
 * WHAT THIS IS NOT FOR. Registration status is *derived* from dates on
 * every request (see lib/races/registration.ts), and both `/races` and the
 * homepage are `force-dynamic`, so the schedule turns over at midnight with
 * no job running at all. Nothing here exists to keep the page correct
 * today.
 *
 * What it does exist for is the three things dates cannot fix by
 * themselves:
 *
 *   1. A manual `registrationStatusOverride` ("full", "cancelled") is the
 *      one piece of state that goes stale, because nobody returns to the
 *      admin panel to clear it once the race has run. Cleared here.
 *   2. Cache. Redundant while the pages are force-dynamic — and exactly
 *      what would keep them correct the day somebody switches either to
 *      ISR, which is a change nobody would think to pair with a cache
 *      revalidation.
 *   3. A data-quality report. There is no official API for race dates, so
 *      every row is hand-curated and drifts. The report is the owner's
 *      actual to-do list; it never edits data.
 *
 * `eventsWithNoEdition` AND `dateless` ARE THE WEEKLY REFRESH'S INPUT, not
 * just this endpoint's own report. `scripts/refresh-race-editions.ts`
 * (docs/race-data-sources.md, "Weekly — the reviewed-CSV refresh") reads
 * this same shape to decide what to re-check, rather than every event in
 * the catalogue every week — the daily job already computed it, so the
 * weekly one doesn't have to.
 *
 * TRIGGERED BY GitHub Actions (.github/workflows/race-schedule-maintenance.yml)
 * rather than a Cloudflare Cron Trigger. A cron trigger needs a `scheduled`
 * handler exported from the Worker, and the Worker entrypoint here is
 * generated by OpenNext — wrapping it means touching the core of the deploy
 * pipeline for one job that runs once a day. This repo already leans on
 * Actions for deploy and e2e, so that is the least surprising home. Worth
 * revisiting once there is a second scheduled job to justify the plumbing.
 */

const STALE_VERIFICATION_DAYS = 90
const MISSING_REGISTRATION_HORIZON_DAYS = 90
const CLOSING_SOON_DAYS = 14

type ReportRow = { id: number; name: string; startDate: string }

const day = (value: unknown): string | null =>
  typeof value === 'string' && value.length >= 10 ? value.slice(0, 10) : null

const shift = (from: Date, days: number): string =>
  new Date(from.getTime() + days * 86_400_000).toISOString().slice(0, 10)

/**
 * Constant-time-ish comparison. Not a defence against a serious timing
 * attack — Workers give no primitive for that — but it does avoid the
 * single-character early exit that `===` on strings compiles to.
 */
function secretMatches(supplied: string, expected: string): boolean {
  if (supplied.length !== expected.length) return false
  let diff = 0
  for (let i = 0; i < supplied.length; i += 1) {
    diff |= supplied.charCodeAt(i) ^ expected.charCodeAt(i)
  }
  return diff === 0
}

function authorise(req: PayloadRequest): void {
  // An admin session is allowed too, so the job can be run by hand from a
  // browser while debugging without the secret being at hand.
  if (isAdminUser(req.user)) return

  const expected = process.env.RACE_MAINTENANCE_SECRET
  if (!expected) {
    throw new APIError('RACE_MAINTENANCE_SECRET is not configured', 500)
  }

  const supplied = req.headers.get('x-maintenance-secret')
  if (!supplied || !secretMatches(supplied, expected)) {
    throw new APIError('Unauthorized', 401)
  }
}

export const raceScheduleMaintenanceEndpoint: Endpoint = {
  path: '/races/maintenance',
  method: 'post',
  handler: async (req) => {
    authorise(req)

    const now = new Date()
    const today = now.toISOString().slice(0, 10)

    // depth 1 to populate `event`: this runs once a day, not on a request
    // path with a query budget, and `race-events` carries no PII (unlike
    // `posts.raceRecord`, which stays at depth 0 for exactly that reason —
    // see lib/content.ts).
    const [all, events] = await Promise.all([
      req.payload.find({
        collection: 'race-editions',
        depth: 1,
        limit: 0,
        pagination: false,
        sort: 'startDate',
        overrideAccess: true,
        req,
      }),
      req.payload.find({
        collection: 'race-events',
        depth: 0,
        limit: 0,
        pagination: false,
        select: { key: true, name: true },
        overrideAccess: true,
        req,
      }),
    ])

    // What data/race-editions.csv's weekly refresh (docs/race-data-sources.md)
    // actually needs to know: which events it has never covered at all. Not
    // itself a data-quality problem — a genuinely unannounced next edition is
    // a normal state (see the PR that first bulk-populated this CSV) — but
    // the count is the input to "did the last refresh make progress",
    // because a growing number here with no corresponding growth in dateless
    // above would mean the refresh stopped running, not that races stopped
    // announcing dates.
    const eventIdsWithEdition = new Set(
      all.docs
        .map((doc) => (typeof doc.event === 'object' ? doc.event?.id : doc.event))
        .filter((id): id is number => typeof id === 'number'),
    )
    const eventsWithNoEdition = events.docs
      .filter((event) => !eventIdsWithEdition.has(event.id))
      .map((event) => ({ id: event.id, key: event.key as string, name: event.name as string }))

    const clearedOverrides: ReportRow[] = []
    const staleVerification: ReportRow[] = []
    const missingRegistration: ReportRow[] = []
    const closingSoon: ReportRow[] = []
    // Every dateless edition, not just the count — see dateless below for
    // why the count alone isn't the signal.
    const dateless: ReportRow[] = []

    const staleBefore = shift(now, -STALE_VERIFICATION_DAYS)
    const registrationHorizon = shift(now, MISSING_REGISTRATION_HORIZON_DAYS)
    const closingHorizon = shift(now, CLOSING_SOON_DAYS)

    for (const doc of all.docs) {
      // A historical edition with no date is not part of a *schedule* — it
      // exists only so a member's record can point at it (RaceEditions.ts)
      // — so it has nothing here to be stale, missing or closing soon.
      const startDate = day(doc.startDate)
      if (!startDate) {
        // Expected in small numbers: a member claiming a historical race
        // with no known date (RaceEditions.ts's own reason `startDate` is
        // optional at all). Not expected in large or fast-growing numbers —
        // that would mean the auto-create path in populateRaceRecordRefs
        // (RaceRecords.ts) is being hit for events the weekly refresh
        // hasn't caught up to yet, or is being abused. The list itself,
        // not just a count, is what makes either case checkable without a
        // direct database query.
        const event = typeof doc.event === 'object' ? doc.event : undefined
        const name = (doc.nameOverride as string | undefined) || event?.name || `edition ${doc.id}`
        dateless.push({ id: doc.id as number, name, startDate: '' })
        continue
      }

      const event = typeof doc.event === 'object' ? doc.event : undefined
      const name = (doc.nameOverride as string | undefined) || event?.name || `edition ${doc.id}`
      const row: ReportRow = { id: doc.id as number, name, startDate }

      if (doc.registrationStatusOverride && startDate < today) {
        await req.payload.update({
          collection: 'race-editions',
          id: doc.id,
          data: { registrationStatusOverride: null },
          depth: 0,
          overrideAccess: true,
          req,
        })
        clearedOverrides.push(row)
      }

      // Everything below reports on races still ahead of us; a past race
      // with missing data is history, not a to-do.
      if (startDate < today) continue

      const verifiedAt = day(doc.verifiedAt)
      if (!verifiedAt || verifiedAt < staleBefore) staleVerification.push(row)

      const opens = day(doc.registrationOpensAt)
      const closes = day(doc.registrationClosesAt)
      if (!opens && !closes && startDate <= registrationHorizon) {
        missingRegistration.push(row)
      }
      if (closes && closes >= today && closes <= closingHorizon) {
        closingSoon.push(row)
      }
    }

    revalidateForRaceSchedule()

    return Response.json({
      checkedAt: now.toISOString(),
      total: all.docs.length,
      clearedOverrides,
      staleVerification,
      missingRegistration,
      closingSoon,
      dateless,
      eventsWithNoEdition,
    })
  },
}
