import { Container } from '@cloudflare/containers'

/**
 * The video transcoder: a Worker whose only job is to own a Container.
 *
 * WHY THIS IS A SEPARATE WORKER. A Cloudflare Container must be a Durable
 * Object, and the Worker the site deploys as is generated by OpenNext from a
 * fixed template that exports only its own three DO classes. There is no
 * documented hook for adding exports, so a Container class cannot live there
 * without editing generated output that the next build would overwrite.
 *
 * It reads better this way regardless: this deploys on its own cadence, its
 * DO migrations never touch the site's D1 migrations, and a transcode that
 * falls over cannot take the site down with it.
 */

type Env = {
  TRANSCODER: DurableObjectNamespace<TranscodeContainer>
  /** Where to report the result. The site's own origin. */
  APP_ORIGIN: string
  /** Shared with the site; proves a callback really came from here. */
  TRANSCODE_SECRET: string
  R2_S3_ENDPOINT: string
  R2_BUCKET: string
  AWS_ACCESS_KEY_ID: string
  AWS_SECRET_ACCESS_KEY: string
}

type TranscodeJob = {
  mediaId: number | string
  sourceUrl: string
  destKey: string
}

type ScriptResult = {
  ok: true
  key: string
  bytes: number
  width: number
  height: number
}

export class TranscodeContainer extends Container<Env> {
  // 4 vCPU is what the 3.11x-realtime measurement was taken at. Disk is not
  // the constraint — the largest source in the corpus is 1.17 GB and peak
  // usage is around 2 GB against this instance type's 20 GB.
  defaultPort = 0
  sleepAfter = '2m'

  /**
   * Run one job to completion, then report the result to the site.
   *
   * Deliberately no retry loop in here. Cloudflare "does not guarantee that
   * any container instance will run for any set period of time", so this
   * process can vanish mid-encode with no chance to report anything — which
   * means retries have to be driven by something that outlives it. That is
   * the lease sweep over `media.transcodeStatus`; adding a second retry
   * mechanism here would just double-run jobs.
   */
  async run(job: TranscodeJob): Promise<void> {
    const started = Date.now()
    try {
      await this.report(job.mediaId, { status: 'running' })

      if (!this.ctx.container?.running) {
        await this.start({
          envVars: {
            AWS_ACCESS_KEY_ID: this.env.AWS_ACCESS_KEY_ID,
            AWS_SECRET_ACCESS_KEY: this.env.AWS_SECRET_ACCESS_KEY,
            R2_BUCKET: this.env.R2_BUCKET,
            R2_S3_ENDPOINT: this.env.R2_S3_ENDPOINT,
          },
        })
      }

      const process = await this.ctx.container!.exec([
        '/usr/local/bin/transcode.sh',
        job.sourceUrl,
        job.destKey,
      ])

      const exitCode = await process.exitCode
      const stdout = await new Response(process.stdout).text()

      if (exitCode !== 0) {
        const stderr = await new Response(process.stderr).text()
        throw new Error(`ffmpeg exited ${exitCode}: ${stderr.slice(0, 500)}`)
      }

      // The script prints exactly one JSON line, last. Anything ffmpeg
      // leaked to stdout before it would otherwise corrupt the parse.
      const line = stdout.trim().split('\n').pop() ?? ''
      const result = JSON.parse(line) as ScriptResult

      await this.report(job.mediaId, {
        bytes: result.bytes,
        height: result.height,
        key: result.key,
        status: 'done',
        width: result.width,
      })
      console.log(
        `transcoded media ${job.mediaId} in ${Date.now() - started}ms -> ${result.bytes} bytes`,
      )
    } catch (error) {
      console.error(`transcode failed for media ${job.mediaId}`, error)
      // Best effort: if this callback also fails, the row stays `running`
      // and the lease sweep reclaims it. Nothing is lost either way.
      await this.report(job.mediaId, {
        message: error instanceof Error ? error.message : String(error),
        status: 'failed',
      }).catch(() => {})
    }
  }

  private async report(
    mediaId: number | string,
    body: Record<string, unknown>,
  ): Promise<void> {
    const response = await fetch(
      `${this.env.APP_ORIGIN}/api/members/media/${mediaId}/transcode-result`,
      {
        body: JSON.stringify(body),
        headers: {
          'Content-Type': 'application/json',
          'x-transcode-secret': this.env.TRANSCODE_SECRET,
        },
        method: 'POST',
      },
    )
    if (!response.ok) {
      throw new Error(`callback for media ${mediaId} returned ${response.status}`)
    }
  }
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url)
    if (request.method !== 'POST' || url.pathname !== '/transcode') {
      return new Response('Not found', { status: 404 })
    }

    const job = (await request.json()) as TranscodeJob
    if (job?.mediaId === undefined || !job.sourceUrl || !job.destKey) {
      return new Response('mediaId, sourceUrl and destKey are required', { status: 400 })
    }

    // One Durable Object per media id, so two dispatches for the same video
    // — a double-click, or the sweep racing a retry — land on the same
    // object and serialize instead of starting two containers on one file.
    const id = env.TRANSCODER.idFromName(String(job.mediaId))
    const stub = env.TRANSCODER.get(id)

    // Not awaited: transcoding a 4K clip measures minutes, and the caller is
    // an upload request. The result arrives by callback.
    void stub.run(job)

    return Response.json({ accepted: true })
  },
}
