import { Container } from '@cloudflare/containers'

/**
 * The video transcoder: a Worker whose only job is to own a Container.
 *
 * WHY THIS IS A SEPARATE WORKER. A Cloudflare Container must be a Durable
 * Object, and the Worker the site deploys as is generated by OpenNext from a
 * fixed template that exports only its own three DO classes. There is no
 * documented hook for adding exports, so a Container class cannot live there
 * without editing generated output that the next build would overwrite.
 *
 * It reads better this way regardless: this deploys on its own cadence, its
 * DO migrations never touch the site's D1 migrations, and a transcode that
 * falls over cannot take the site down with it.
 */

type Env = {
  TRANSCODER: DurableObjectNamespace<TranscodeContainer>
  /** Where to report the result. The site's own origin. */
  APP_ORIGIN: string
  /**
   * Shared with the site. It proves a callback really came from here, and
   * — since this Worker answers on a public hostname — that a job request
   * really came from the site.
   */
  TRANSCODE_SECRET: string
  R2_S3_ENDPOINT: string
  R2_BUCKET: string
  AWS_ACCESS_KEY_ID: string
  AWS_SECRET_ACCESS_KEY: string
}

/**
 * What a caller may ask for. `destKey` is NOT part of it, deliberately —
 * see `destKeyFor` below.
 */
type TranscodeJob = {
  mediaId: number | string
  sourceUrl: string
}

/**
 * A member picked a frame and wants it as the cover.
 *
 * `seconds` is the only caller-supplied value that reaches ffmpeg, and it is
 * re-validated here rather than trusted from the site — this Worker answers
 * on a public hostname, so "the site checked it" is not a property this code
 * can rely on. Where the frame is written is still derived from the media id,
 * never sent.
 */
type PosterJob = {
  mediaId: number | string
  sourceUrl: string
  seconds: number
}

type ScriptResult = {
  ok: true
  /** Set when the source already met the target and nothing was encoded. */
  skipped?: boolean
  reason?: string
  key?: string
  bytes?: number
  width?: number
  height?: number
  /**
   * Absent when the frame could not be taken or could not be uploaded. The
   * script treats a poster as an improvement rather than part of the job, so
   * these three are optional on BOTH outcomes — including `skipped`, which is
   * the path most of the corpus takes and therefore the one that matters most
   * for ever getting a poster at all.
   */
  posterKey?: string
  posterWidth?: number
  posterHeight?: number
}

export class TranscodeContainer extends Container<Env> {
  // 4 vCPU is what the 3.11x-realtime measurement was taken at. Disk is not
  // the constraint — the largest source in the corpus is 1.17 GB and peak
  // usage is around 2 GB against this instance type's 20 GB.
  //
  // NO `defaultPort`. This container never serves HTTP — everything happens
  // over `this.ctx.container.exec()` below — and `defaultPort = 0` was tried
  // first to say so, which broke startup outright. `this.start()` computes
  // `portToCheck` as `defaultPort ?? fallback`, and 0 is not nullish, so it
  // was used as a real port: `container.getTcpPort(0)` validates its
  // argument as an actual TCP port number and throws `Invalid port number: 0`
  // synchronously, OUTSIDE the library's own retry/catch — every start
  // failed on its first and only attempt, reported as a transcode failure
  // with that exact message.
  //
  // Leaving this unset lets `getPortsToCheck` fall back to its own constant
  // (port 33, nothing listens there on purpose). That is deliberate library
  // behaviour for exactly this shape of container: `doStartContainer` treats
  // "connection refused but the container process is running" as success —
  // see `isNotListeningError` in @cloudflare/containers. That graceful path
  // only exists downstream of a valid port number, which 0 never reached.
  // 30m, not the 2m this started at, and the reason is not "encodes are
  // slow" — it is that the library cannot see this container working at all.
  //
  // `renewActivityTimeout()` is called by the library on exactly three
  // things: a proxied HTTP request, a WebSocket message, and container
  // startup. This container serves no HTTP and no WebSockets; every job runs
  // through `this.ctx.container.exec()`, which is the RAW Durable Object
  // container API and bypasses the library entirely. So from the library's
  // point of view a running encode looks like a container nobody has touched
  // since it booted, and `sleepAfter` stops it mid-work — logged locally as
  // a stream of "Activity expired, signalling container to stop" while
  // ffmpeg was still going.
  //
  // The heartbeat in `run()` below is the real fix; this larger window is
  // the belt to its braces, sized past any plausible encode (the corpus's
  // largest file measured ~4 minutes end to end).
  sleepAfter = '30m'

  /**
   * Accept a job and return immediately.
   *
   * The split exists because of a bug that lost every single transcode. The
   * Worker used to call `void stub.run(job)` — an RPC that was never
   * awaited — and Cloudflare's rules of Durable Objects say plainly that
   * "unawaited calls create dangling promises" and that an async call
   * "neither awaited nor passed to ctx.waitUntil() can be canceled when the
   * invocation ends". It was: the row stayed `queued`, no Durable Object
   * invocation was recorded at all, and nothing anywhere logged a reason.
   *
   * So the caller awaits THIS, which returns as soon as the job is handed
   * over. It is named `accept` rather than `start` because `Container`
   * already defines `start()` — the one that boots the container, called
   * inside `run` below. The first version of this fix shadowed it, and
   * typecheck caught the signature clash; at runtime it would have booted
   * nothing. `run` is deliberately not awaited here — inside a Durable Object
   * that is the documented way to keep going, because a DO "remains active
   * as long as there is ongoing work or pending I/O" and `waitUntil` is
   * explicitly a no-op. Awaiting it would hold an upload request open for
   * the length of an encode, which is the thing this whole design avoids.
   *
   * If the object is evicted mid-encode anyway, that is what the lease and
   * the sweep are for — the same recovery path a killed container needs.
   */
  async accept(job: TranscodeJob): Promise<void> {
    void this.run(job)
  }

  /** The poster-only equivalent of `accept`, and detached for the same reason. */
  async acceptPoster(job: PosterJob): Promise<void> {
    void this.runPoster(job)
  }

  /**
   * Take one frame at the time a member chose, and report it.
   *
   * Deliberately does NOT touch `transcodeStatus` at either end — no
   * `running`, no `done`. Choosing a cover picture says nothing about whether
   * the video was transcoded, and routing this through the transcode callback
   * would relabel a genuinely transcoded video as `skipped`, which is the trap
   * scripts/backfill-video-posters.ts already refuses to walk into.
   *
   * The consequence is that there is no lease and therefore no sweep to
   * recover this: if the container dies mid-frame, nothing retries. That is
   * the right trade for work a member started by pressing a button and can
   * simply press again — a lease exists so an upload nobody is watching still
   * finishes, and this is the opposite situation.
   */
  async runPoster(job: PosterJob): Promise<void> {
    try {
      const containerEnv = {
        AWS_ACCESS_KEY_ID: this.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: this.env.AWS_SECRET_ACCESS_KEY,
        R2_BUCKET: this.env.R2_BUCKET,
        R2_S3_ENDPOINT: this.env.R2_S3_ENDPOINT,
      }

      if (!this.ctx.container?.running) {
        await this.start({ envVars: containerEnv })
      }

      const process = await this.ctx.container!.exec(
        [
          '/usr/local/bin/poster.sh',
          job.sourceUrl,
          posterKeyFor(job.mediaId),
          String(job.seconds),
        ],
        { env: containerEnv },
      )

      // Same heartbeat as `run`, same reason: `exec()` is the raw container
      // API, so the library's inactivity timer would otherwise stop the
      // container while ffmpeg is still seeking a long file.
      const heartbeat = setInterval(() => this.renewActivityTimeout(), 30_000)
      let exitCode: number
      let stdout: string
      try {
        stdout = await new Response(process.stdout).text()
        exitCode = await process.exitCode
      } finally {
        clearInterval(heartbeat)
      }

      if (exitCode !== 0) {
        const stderr = await new Response(process.stderr).text()
        throw new Error(`poster.sh exited ${exitCode}: ${stderr.slice(0, 500)}`)
      }

      const line = stdout.trim().split('\n').filter(Boolean).pop() ?? ''
      const result = JSON.parse(line) as ScriptResult
      if (!result?.posterKey) {
        throw new Error('poster.sh reported no posterKey')
      }

      await this.reportPoster(job.mediaId, {
        ok: true,
        posterHeight: result.posterHeight,
        posterKey: result.posterKey,
        posterWidth: result.posterWidth,
        seconds: job.seconds,
      })
    } catch (error) {
      const reason = error instanceof Error ? error.message : String(error)
      await this.ctx.container?.destroy(reason).catch(() => {})
      // Best effort, like `run`'s: the member sees the poster not change and
      // can press again, which is the whole recovery story for this path.
      await this.reportPoster(job.mediaId, { message: reason, ok: false }).catch(() => {})
    }
  }

  /**
   * Run one job to completion, then report the result to the site.
   *
   * Deliberately no retry loop in here. Cloudflare "does not guarantee that
   * any container instance will run for any set period of time", so this
   * process can vanish mid-encode with no chance to report anything — which
   * means retries have to be driven by something that outlives it. That is
   * the lease sweep over `media.transcodeStatus`; adding a second retry
   * mechanism here would just double-run jobs.
   */
  async run(job: TranscodeJob): Promise<void> {
    const started = Date.now()
    try {
      await this.report(job.mediaId, { status: 'running' })

      // Passed on BOTH paths, and that redundancy is the fix for four
      // identical failures in a row.
      //
      // `start()` only runs when the container is not already running, and
      // its `envVars` apply to that start only. But a Container DO restarts
      // its container on its own — the base class keeps a perpetual alarm
      // and boots the container from lifecycle paths this code never calls.
      // When that happened first, `run` found `container.running` already
      // true, skipped `start()` entirely, and exec'd into a process tree
      // that had been started with no `env` at all. The container was real
      // and healthy, ffmpeg ran fine, and the script died on the one line
      // that needed a variable nobody had set: `R2_S3_ENDPOINT`.
      //
      // `exec`'s own `env` does not depend on how the container came up.
      // Cloudflare's docs: "The process inherits existing Container
      // variables. Matching keys use the per-execution value." So this is
      // the authoritative one; the `start()` copy stays because it is
      // correct for a cold boot and costs nothing.
      const containerEnv = {
        AWS_ACCESS_KEY_ID: this.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: this.env.AWS_SECRET_ACCESS_KEY,
        R2_BUCKET: this.env.R2_BUCKET,
        R2_S3_ENDPOINT: this.env.R2_S3_ENDPOINT,
      }

      if (!this.ctx.container?.running) {
        await this.start({ envVars: containerEnv })
      }

      const process = await this.ctx.container!.exec(
        [
          '/usr/local/bin/transcode.sh',
          job.sourceUrl,
          destKeyFor(job.mediaId),
          posterKeyFor(job.mediaId),
        ],
        { env: containerEnv },
      )

      // Tell the library the container is busy, because nothing else will.
      // `exec()` is the raw container API and the library never sees it, so
      // without this its inactivity timer runs down during the encode and
      // stops the container out from under ffmpeg. Cleared in `finally` so a
      // finished job goes back to idling and shuts down on schedule.
      const heartbeat = setInterval(() => this.renewActivityTimeout(), 30_000)

      let exitCode: number
      let stdout: string
      try {
        // stdout is drained BEFORE awaiting the exit code. The script's
        // output is one short JSON line so the pipe would not fill, but the
        // documented shape is to read output rather than block on exit
        // first, and a process that fills its stdout buffer while nobody
        // reads it never exits at all.
        stdout = await new Response(process.stdout).text()
        exitCode = await process.exitCode
      } finally {
        clearInterval(heartbeat)
      }

      if (exitCode !== 0) {
        const stderr = await new Response(process.stderr).text()
        // "transcode.sh", not "ffmpeg": this is the SCRIPT's exit code, and
        // under `set -eu` it can come from curl, ffprobe or the upload just
        // as easily. Reporting every one of them as an ffmpeg failure sent
        // members looking at their video for a problem that was not there.
        throw new Error(`transcode.sh exited ${exitCode}: ${stderr.slice(0, 500)}`)
      }

      // The script prints exactly one JSON line, last. Anything ffmpeg
      // leaked to stdout before it would otherwise corrupt the parse.
      const line = stdout.trim().split('\n').pop() ?? ''
      const result = JSON.parse(line) as ScriptResult

      // Reported on both outcomes, because the script takes the frame before
      // it decides whether to encode. Spread rather than always sent, so a
      // run that could not produce one leaves whatever the row already has
      // alone instead of writing nulls over it.
      const poster = result.posterKey
        ? {
            posterKey: result.posterKey,
            posterHeight: result.posterHeight,
            posterWidth: result.posterWidth,
          }
        : {}

      if (result.skipped) {
        // No new object exists, so there is nothing to repoint the row at.
        // `skipped` is the honest state and the media keeps serving the file
        // it already had — which is why this is the cheapest possible
        // outcome rather than a special case to work around.
        await this.report(job.mediaId, { ...poster, status: 'skipped' })
        console.log(
          `media ${job.mediaId} needed no transcode (${result.reason ?? 'already compliant'})`,
        )
      } else {
        await this.report(job.mediaId, {
          ...poster,
          bytes: result.bytes,
          height: result.height,
          key: result.key,
          status: 'done',
          width: result.width,
        })
        console.log(
          `transcoded media ${job.mediaId} in ${Date.now() - started}ms -> ${result.bytes} bytes`,
        )
      }

      // Hand the slot back now that the work is done, instead of letting
      // `sleepAfter` get round to it.
      //
      // Raising `sleepAfter` to 30m stopped the library killing a container
      // mid-encode, and immediately caused the opposite failure: two short
      // videos transcoded successfully, then sat `running` for half an hour
      // holding both `max_instances` slots, so the next upload — a 1.04 GB
      // file — could not start at all ("Maximum number of running container
      // instances exceeded"). The inactivity timer is the wrong instrument
      // for this: it exists to catch a container nobody told about, and this
      // code knows exactly when the job finished.
      //
      // `stop()` rather than `destroy()`: SIGTERM lets the process exit
      // cleanly, and there is nothing to race — the output is already in R2
      // and the callback has already landed. The failure path still uses
      // `destroy()`, where a stuck process is the likely reason for being
      // there at all.
      await this.stop().catch(() => {})
    } catch (error) {
      console.error(`transcode failed for media ${job.mediaId}`, error)

      const reason = error instanceof Error ? error.message : String(error)

      // Some failures are about this video; this one is about the moment.
      // "Maximum number of running container instances exceeded" means the
      // account was busy, and says nothing at all about the file — it will
      // very likely succeed on the next attempt. Reporting `failed` for it
      // made a member's upload terminal for a reason they could neither see
      // nor influence, and left retrying to them by hand.
      //
      // Two kinds of "not this video's fault", both of which used to end a
      // member's upload permanently with a message they could do nothing
      // about.
      //
      //   - the account was at its container limit
      //   - the container was signalled away mid-run: 137 is 128+9 (SIGKILL)
      //     and 143 is 128+15 (SIGTERM), which is exactly the sequence
      //     Cloudflare documents for stopping an instance — a host restart,
      //     or an image rollout. Deploying this Worker while a transcode was
      //     running produced `transcode.sh exited 137` twice in one session,
      //     and each time it reached the member as a failure email about
      //     their file.
      //
      // Both go back to `queued`, where the sweep re-dispatches them.
      //
      // UNBOUNDED, and deliberately stated rather than implied. An earlier
      // version of this comment claimed the reclaim path counts attempts so
      // a video landing here "eventually stops"; that was wrong. Reading
      // transcodeSweep.ts: `transcodeAttempts` is incremented only in the
      // `running` branch, via `reclaim()` on an expired lease. A row that
      // reports `queued` is already past that branch by the time the sweep
      // sees it, so it is re-dispatched with no increment — every 15
      // minutes, indefinitely.
      //
      // That is the right behaviour for a condition that really is
      // temporary: you want it to keep trying until a slot frees. It is the
      // wrong behaviour if the condition becomes permanent (max_instances
      // set to zero, an account-level limit), because nothing then bounds
      // the retries and nothing tells anyone — the member sees 等待轉檔
      // forever and no mail is sent. At three instances for a club posting
      // a few videos a month that trade is fine; if it stops being fine,
      // the fix is to count attempts on this path too, not to make the
      // failure terminal again.
      const busy = /Maximum number of running container instances/i.test(reason)
      const signalled = /exited (137|143)\b/.test(reason)
      const transient = busy || signalled

      // A failed job used to leave its container running. `max_instances`
      // on this Worker is deliberately low — 2 on staging — specifically to
      // cap what a runaway retry can spend, so three real test uploads
      // (673, 674, 675) each starting their own container was enough to
      // hit "Maximum number of running container instances exceeded" on the
      // very next one. Every prior fix in this file added a missing
      // capability; this is the one that stops a leak instead. It also
      // means a retry never reuses a container that limped partway through
      // an old failure with stale state.
      await this.ctx.container?.destroy(reason).catch(() => {})

      // Best effort: if this callback also fails, the row stays `running`
      // and the lease sweep reclaims it. Nothing is lost either way.
      await this.report(job.mediaId, {
        message: reason,
        status: transient ? 'queued' : 'failed',
      }).catch(() => {})
    }
  }

  /**
   * A separate callback from `report`, addressed to a separate endpoint.
   *
   * The site's `/transcode-result` requires a transcode status and writes it;
   * there is no value of that field which means "I only chose a picture". So
   * the poster path reports to `/poster-result`, which touches `posterUrl`
   * and nothing else.
   */
  private async reportPoster(
    mediaId: number | string,
    body: Record<string, unknown>,
  ): Promise<void> {
    const response = await fetch(
      `${this.env.APP_ORIGIN}/api/members/media/${mediaId}/poster-result`,
      {
        body: JSON.stringify(body),
        headers: {
          'Content-Type': 'application/json',
          'x-transcode-secret': this.env.TRANSCODE_SECRET,
        },
        method: 'POST',
      },
    )
    if (!response.ok) {
      throw new Error(`poster callback for media ${mediaId} returned ${response.status}`)
    }
  }

  private async report(
    mediaId: number | string,
    body: Record<string, unknown>,
  ): Promise<void> {
    const response = await fetch(
      `${this.env.APP_ORIGIN}/api/members/media/${mediaId}/transcode-result`,
      {
        body: JSON.stringify(body),
        headers: {
          'Content-Type': 'application/json',
          'x-transcode-secret': this.env.TRANSCODE_SECRET,
        },
        method: 'POST',
      },
    )
    if (!response.ok) {
      throw new Error(`callback for media ${mediaId} returned ${response.status}`)
    }
  }
}

/**
 * Where the transcode is written. Derived from the media id HERE, never
 * taken from the request.
 *
 * It used to be a request field, and that was a hole rather than a
 * shortcut: this handler had no authentication at all and Cloudflare gave
 * it a public `workers.dev` hostname, so anyone who knew the URL could post
 * a key of their choosing and have the container write over any object in
 * the bucket, using this Worker's own R2 credentials. Deriving it removes
 * the primitive instead of guarding it.
 *
 * Kept in step with `transcodedKey()` in src/lib/media/transcode-state.ts by
 * hand — a separate Worker cannot import from the app. If one changes, the
 * transcode lands somewhere the site never looks, so change both.
 */
function destKeyFor(mediaId: number | string): string {
  return `transcoded/${mediaId}-1080p.mp4`
}

/**
 * Where the poster frame is written — derived here for exactly the reason
 * `destKeyFor` is, and kept in step with `posterKey()` in
 * src/lib/media/transcode-state.ts by hand.
 *
 * A separate prefix from `transcoded/`, not a sibling extension, so the
 * unused-media sweep and any bucket-level rule can tell one from the other
 * without parsing a filename.
 */
function posterKeyFor(mediaId: number | string): string {
  return `posters/${mediaId}.jpg`
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url)
    const isTranscode = request.method === 'POST' && url.pathname === '/transcode'
    const isPoster = request.method === 'POST' && url.pathname === '/poster'
    if (!isTranscode && !isPoster) {
      return new Response('Not found', { status: 404 })
    }

    // The site reaches this over a service binding, which needs no
    // hostname — but Cloudflare publishes one anyway, so this handler is
    // on the open internet and has to say who may use it. An unset secret
    // refuses everything rather than defaulting to open, exactly as the
    // site's own /transcode-result callback does.
    if (!env.TRANSCODE_SECRET || request.headers.get('x-transcode-secret') !== env.TRANSCODE_SECRET) {
      return new Response('Unauthorized', { status: 401 })
    }

    const job = (await request.json()) as TranscodeJob & { seconds?: unknown }
    if (job?.mediaId === undefined || !job.sourceUrl) {
      return new Response('mediaId and sourceUrl are required', { status: 400 })
    }

    // The container fetches this itself. Requiring https keeps a leaked
    // secret from turning into a fetch of anything reachable from
    // Cloudflare's network.
    if (!job.sourceUrl.startsWith('https://')) {
      return new Response('sourceUrl must be https', { status: 400 })
    }

    // Re-validated here, not trusted from the site: `seconds` is the one
    // caller-supplied value that reaches ffmpeg's argv, and this handler is
    // on the open internet. Finite, non-negative, and bounded well past any
    // plausible club video — a NaN or an Infinity would otherwise be
    // stringified straight into the command.
    let seconds = 0
    if (isPoster) {
      const raw = typeof job.seconds === 'number' ? job.seconds : Number(job.seconds)
      if (!Number.isFinite(raw) || raw < 0 || raw > 86_400) {
        return new Response('seconds must be a finite number between 0 and 86400', {
          status: 400,
        })
      }
      seconds = Math.round(raw * 1000) / 1000
    }

    // One Durable Object per media id, so two dispatches for the same video
    // — a double-click, or the sweep racing a retry, or a poster request
    // arriving mid-encode — land on the same object and serialize instead of
    // starting two containers on one file.
    const id = env.TRANSCODER.idFromName(String(job.mediaId))
    const stub = env.TRANSCODER.get(id)

    // Awaited, and `accept` is the fast half on purpose — see its header. The
    // previous version called `run` here without awaiting it and every
    // transcode was silently dropped.
    if (isPoster) {
      await stub.acceptPoster({ mediaId: job.mediaId, seconds, sourceUrl: job.sourceUrl })
    } else {
      await stub.accept(job)
    }

    return Response.json({ accepted: true })
  },
}
