import { readFileSync } from "node:fs";

import { expect, test } from "@playwright/test";

import { GLOSSARY, toSimplified, toTraditional } from "../../scripts/lib/zh-convert";
import { generate } from "../../scripts/generate-zh-hans";

/**
 * U-CONVERT — 繁 ↔ 簡, and the one dictionary that is generated by it.
 *
 * WHY THIS IS TESTED AT ALL when the conversion itself is OpenCC's. Not to
 * re-check a vendor's dictionaries — `docs/testing-strategy.md` rules that
 * out. What is ours here is the *configuration*: which variant we convert
 * between, the glossary that sits on top, and the claim that the committed
 * Simplified dictionary is what this configuration produces. All three are
 * things a change to this repo can get wrong, and none of them is visible on
 * a rendered page: a Simplified reader would just see a slightly wrong word.
 *
 * The 簡 → 繁 direction is not used by anything that ships today — it is what
 * an article written in Simplified will need. It is tested now because the
 * one-to-many characters are the whole reason this is a library call and not
 * a character table, and an assertion written after the code that depends on
 * it is an assertion written to pass.
 */

test.describe("U-CONVERT the 繁簡 converter", () => {
  test("U-CONVERT-1: 繁 → 簡 converts the script and leaves everything else alone", () => {
    expect(toSimplified("關於野馬營")).toBe("关于野马营");
    expect(toSimplified("賽事")).toBe("赛事");
    expect(toSimplified("穿越時光")).toBe("穿越时光");
    // Placeholders and Latin text are not Han and must survive untouched —
    // every interpolated string in the dictionary depends on it.
    expect(toSimplified("{count} 張照片")).toBe("{count} 张照片");
    expect(toSimplified("下載 PDF")).toBe("下载 PDF");
  });

  test("U-CONVERT-2: 簡 → 繁 picks the right form of a one-to-many character", () => {
    // The reason this is OpenCC and not a character map. Each pair below has
    // the same Simplified character standing for two different Traditional
    // ones, and only the word decides which.
    expect(toTraditional("头发")).toBe("頭髮");
    expect(toTraditional("出发")).toBe("出發");
    expect(toTraditional("干活")).toBe("幹活");
    expect(toTraditional("干净")).toBe("乾淨");
    expect(toTraditional("饼干")).toBe("餅乾");
    expect(toTraditional("后面")).toBe("後面");
    expect(toTraditional("皇后")).toBe("皇后");
  });

  test("U-CONVERT-3: the committed Simplified dictionary is what the generator produces", () => {
    // The check that keeps a hand-edit to zh-Hans.json from surviving, and
    // keeps a new Traditional string from shipping with no Simplified one.
    const generated = generate(readFileSync("src/dictionaries/zh-Hant.json", "utf8"));
    expect(
      readFileSync("src/dictionaries/zh-Hans.json", "utf8"),
      "run `pnpm generate:zh-hans` — the committed Simplified dictionary is stale",
    ).toBe(generated);
  });

  test("U-CONVERT-4: the glossary only fixes what conversion alone gets wrong", () => {
    // 轉檔 converts character-by-character into 转档, which is not a word.
    expect(toSimplified("影片正在轉檔")).toBe("影片正在转码");
    // The site says both 相冊 and 相簿 for one thing; Simplified is where
    // they stop disagreeing.
    expect(toSimplified("相冊")).toBe("相册");
    expect(toSimplified("相簿")).toBe("相册");

    // And the rule the glossary is deliberately NOT allowed to grow past:
    // Taiwanese vocabulary that converts to real Simplified words is left
    // alone, because articles go through this same converter and the
    // interface must not develop a second vocabulary for one thing.
    expect(toSimplified("影片")).toBe("影片");
    expect(toSimplified("資訊")).toBe("资讯");
    expect(toSimplified("裝置")).toBe("装置");
    expect(GLOSSARY.toSimplified.length).toBeLessThanOrEqual(4);
  });
});
