// This file is generated by Velite

export { default as posts } from './posts.json' with { type: 'json' }
export { default as galleries } from './galleries.json' with { type: 'json' }
export { default as authors } from './authors.json' with { type: 'json' }
export { default as globals } from './globals.json' with { type: 'json' }