import type { Payload } from 'payload'
import { getCloudflareContext } from '@opennextjs/cloudflare'

/**
 * Hand a queued job to the transcoder.
 *
 * The transcoder is a SEPARATE WORKER, reached over a service binding, and
 * that is forced rather than chosen. A Cloudflare Container must be a
 * Durable Object, and the Worker this app deploys as is generated by
 * OpenNext from a fixed template that exports only its own three DO classes
 * (`DOQueueHandler`, `DOShardedTagCache`, `BucketCachePurge`).
 * `@opennextjs/cloudflare` offers no hook for adding exports, so a Container
 * class cannot live in this Worker without editing generated output — which
 * the next build would overwrite.
 *
 * Splitting it out turns out to be the better shape anyway: the transcoder
 * deploys on its own cadence, its Durable Object migrations never touch this
 * app's D1 migrations, and a broken transcode cannot take the site down.
 *
 * Every failure is swallowed into `false`. The upload has already succeeded
 * by the time this runs, so a transcoder that is unreachable must not make
 * the request look failed — the row stays `queued` and the scheduled sweep
 * retries it. That is the same rule `processMediaImage.ts` states for the
 * image path.
 */
export async function startTranscode(args: {
  mediaId: number | string
  payload: Payload
}): Promise<boolean> {
  try {
    const { env } = await getCloudflareContext({ async: true })
    const transcoder = (env as unknown as { TRANSCODER?: Fetcher }).TRANSCODER

    if (!transcoder) {
      // Expected in local dev and in CI, where the transcoder Worker is not
      // running. Not an error: the row is already `queued`, which is the
      // honest state, and nothing has been lost.
      return false
    }

    const response = await transcoder.fetch('https://transcoder/transcode', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ mediaId: args.mediaId }),
    })

    if (!response.ok) {
      console.warn(
        `transcode dispatch for media ${args.mediaId} returned ${response.status}`,
      )
      return false
    }
    return true
  } catch (error) {
    console.warn(`transcode dispatch for media ${args.mediaId} failed`, error)
    return false
  }
}
