/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    posts: Post;
    galleries: Gallery;
    'race-events': RaceEvent;
    'race-categories': RaceCategory;
    'race-editions': RaceEdition;
    'race-records': RaceRecord;
    'race-schedule': RaceSchedule;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    'race-events': RaceEventsSelect<false> | RaceEventsSelect<true>;
    'race-categories': RaceCategoriesSelect<false> | RaceCategoriesSelect<true>;
    'race-editions': RaceEditionsSelect<false> | RaceEditionsSelect<true>;
    'race-records': RaceRecordsSelect<false> | RaceRecordsSelect<true>;
    'race-schedule': RaceScheduleSelect<false> | RaceScheduleSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Seeds the author alias shown on the site. The alias itself lives on the author record.
   */
  displayName?: string | null;
  /**
   * Byline this account publishes under. Created automatically; edit the alias on the author record itself.
   */
  author?: (number | null) | Author;
  /**
   * Cleared automatically the first time they sign in.
   */
  invitePending?: boolean | null;
  invitedAt?: string | null;
  invitedBy?: (number | null) | User;
  /**
   * Overrides the default (10240 MB) for this account. Leave blank to use the default.
   */
  storageQuotaMb?: number | null;
  /**
   * Admins manage everything; members only their own content.
   */
  role: 'admin' | 'member';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * Whoever created this. Only admins can reassign it.
   */
  owner?: (number | null) | User;
  name: string;
  slug: string;
  bio?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Whoever created this. Only admins can reassign it.
   */
  owner?: (number | null) | User;
  alt: string;
  /**
   * Optional. Which race this photo is from — shown on that race’s public photo wall.
   */
  raceEdition?: (number | null) | RaceEdition;
  /**
   * Cloudflare Stream UID after video ingest (Phase 5+)
   */
  streamId?: string | null;
  /**
   * Cloudflare Stream has finished processing this video
   */
  streamReady?: boolean | null;
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * One row per running of a race. A row with no start date is a historical edition somebody has a record for — that is expected, not missing data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "race-editions".
 */
export interface RaceEdition {
  id: number;
  event: number | RaceEvent;
  year: number;
  /**
   * Empty for a historical edition nobody recorded the dates of. It will not appear on /races, which is correct — it exists so a record can point at it.
   */
  startDate?: string | null;
  /**
   * Multi-day events only. Leave empty for a single day.
   */
  endDate?: string | null;
  /**
   * Only when this edition was published under a different name than the event carries now. Otherwise leave empty and the event name is used.
   */
  nameOverride?: string | null;
  location?: string | null;
  /**
   * Only if this edition has its own page. The event's own website lives on the event.
   */
  url?: string | null;
  /**
   * Leave empty if not announced. Never guess — a wrong date makes people miss entry.
   */
  registrationOpensAt?: string | null;
  registrationClosesAt?: string | null;
  registrationUrl?: string | null;
  registrationType?: ('first-come' | 'lottery' | 'qualifier' | 'invitational') | null;
  /**
   * Only for what dates cannot express. Clear it once the race has run — the daily maintenance job clears stale ones.
   */
  registrationStatusOverride?: ('full' | 'waitlist' | 'cancelled' | 'tba') | null;
  sourceUrl?: string | null;
  verifiedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The race itself. Dates live on editions. Renaming is fine; changing the key is not — a member badge points at it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "race-events".
 */
export interface RaceEvent {
  id: number;
  /**
   * Stable identifier, e.g. utmb-mont-blanc. Immutable — the badge colour is derived from it and member records point at it.
   */
  key: string;
  name: string;
  /**
   * Only where Chinese runners actually use one. The site shows this instead of the name, so a transliteration nobody uses would hide the race.
   */
  nameZh?: string | null;
  /**
   * Changes between seasons — races join and leave. Re-check it when the next calendar is published.
   */
  series: 'utmb' | 'wtm' | 'others';
  /**
   * ISO 3166-1 alpha-3, e.g. FRA.
   */
  country?: string | null;
  /**
   * Empty is allowed only when there genuinely is none — the Barkley has no site at all. Say so in Source.
   */
  website?: string | null;
  /**
   * itra.run/Races/RaceDetails/<id>. The race pages are plain HTML; the calendar is not, so use the race page.
   */
  itraUrl?: string | null;
  source?: string | null;
  /**
   * The day somebody read the source. Empty means never. Do not bump it for rows you did not actually re-read.
   */
  verifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Whoever created this. Only admins can reassign it.
   */
  owner?: (number | null) | User;
  title: string;
  /**
   * Public path segment, e.g. 2024/utmb → /posts/2024/utmb
   */
  slug: string;
  description: string;
  image?: (number | null) | Media;
  author?: (number | null) | Author;
  featured?: boolean | null;
  publishedAt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  /**
   * Whoever created this. Only admins can reassign it.
   */
  owner?: (number | null) | User;
  name: string;
  slug: string;
  location?: string | null;
  featured?: boolean | null;
  eventDate?: string | null;
  cover?: (number | null) | Media;
  images?:
    | {
        media: number | Media;
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  videos?:
    | {
        media: number | Media;
        /**
         * Stable public id for /gallery/[slug]/v/[videoId]
         */
        videoId?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "race-categories".
 */
export interface RaceCategory {
  id: number;
  event: number | RaceEvent;
  /**
   * Stable within the event, e.g. ccc, 100m, relay. Member records point at it — rename the label, not this.
   */
  key: string;
  /**
   * What the race calls it, shown on the badge band: "CCC", "TMiler", "接力".
   */
  label: string;
  /**
   * The real distance, which often differs from the name — Kaçkar's "100K" is 82 km. Leave empty rather than deriving it from the label.
   */
  distanceKm?: number | null;
  elevationGainM?: number | null;
  /**
   * Longest first, matching how events list their own races.
   */
  order?: number | null;
  /**
   * Ticked only if somebody read the event's own site. Unticked means assumed, and assumed has been wrong every time it was checked.
   */
  verified?: boolean | null;
  source?: string | null;
  verifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "race-records".
 */
export interface RaceRecord {
  id: number;
  /**
   * Whoever created this. Only admins can reassign it.
   */
  owner?: (number | null) | User;
  eventId: string;
  distanceId: string;
  year: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upcoming races shown on /races. Dates and registration windows change often — leave a field empty rather than guessing, and update "Verified on" whenever you check a row against the official site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "race-schedule".
 */
export interface RaceSchedule {
  id: number;
  /**
   * Stored even when linked to a catalogue event — renaming a catalogue entry must not rewrite a published schedule.
   */
  name: string;
  nameZh?: string | null;
  series: 'utmb' | 'wtm' | 'others';
  startDate: string;
  /**
   * Multi-day events only. Leave empty for a single day.
   */
  endDate?: string | null;
  /**
   * Optional. An id from the race catalogue (e.g. utmb-mont-blanc). Only controls whether a badge is shown next to this race.
   */
  eventId?: string | null;
  /**
   * ISO 3166-1 alpha-3, e.g. FRA.
   */
  country?: string | null;
  location?: string | null;
  /**
   * Free text, e.g. "20K / 50K / 100K / 100M". Deliberately not the catalogue distance enum, so a race outside the catalogue can still be scheduled.
   */
  distanceSummary?: string | null;
  /**
   * Full address including https://
   */
  url?: string | null;
  /**
   * Leave empty if not announced. Never guess — a wrong date makes people miss entry.
   */
  registrationOpensAt?: string | null;
  registrationClosesAt?: string | null;
  /**
   * Separate from the official site — many races register through a third-party platform. Falls back to the official site when empty.
   */
  registrationUrl?: string | null;
  /**
   * Hardrock, Western States and UTMB Mont-Blanc are lotteries — saying only "open" would mislead.
   */
  registrationType?: ('first-come' | 'lottery' | 'qualifier' | 'invitational') | null;
  /**
   * Only for what dates cannot express. Setting this overrides the date-derived status, so clear it once the race has run — the daily maintenance job clears stale ones.
   */
  registrationStatusOverride?: ('full' | 'waitlist' | 'cancelled' | 'tba') | null;
  /**
   * Where this row was copied from. For re-checking later, not shown to visitors.
   */
  sourceUrl?: string | null;
  /**
   * Set to today whenever you check this row against the official site.
   */
  verifiedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'race-events';
        value: number | RaceEvent;
      } | null)
    | ({
        relationTo: 'race-categories';
        value: number | RaceCategory;
      } | null)
    | ({
        relationTo: 'race-editions';
        value: number | RaceEdition;
      } | null)
    | ({
        relationTo: 'race-records';
        value: number | RaceRecord;
      } | null)
    | ({
        relationTo: 'race-schedule';
        value: number | RaceSchedule;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  author?: T;
  invitePending?: T;
  invitedAt?: T;
  invitedBy?: T;
  storageQuotaMb?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  owner?: T;
  alt?: T;
  raceEdition?: T;
  streamId?: T;
  streamReady?: T;
  blurDataURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  owner?: T;
  name?: T;
  slug?: T;
  bio?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  owner?: T;
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  author?: T;
  featured?: T;
  publishedAt?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  owner?: T;
  name?: T;
  slug?: T;
  location?: T;
  featured?: T;
  eventDate?: T;
  cover?: T;
  images?:
    | T
    | {
        media?: T;
        featured?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        media?: T;
        videoId?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "race-events_select".
 */
export interface RaceEventsSelect<T extends boolean = true> {
  key?: T;
  name?: T;
  nameZh?: T;
  series?: T;
  country?: T;
  website?: T;
  itraUrl?: T;
  source?: T;
  verifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "race-categories_select".
 */
export interface RaceCategoriesSelect<T extends boolean = true> {
  event?: T;
  key?: T;
  label?: T;
  distanceKm?: T;
  elevationGainM?: T;
  order?: T;
  verified?: T;
  source?: T;
  verifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "race-editions_select".
 */
export interface RaceEditionsSelect<T extends boolean = true> {
  event?: T;
  year?: T;
  startDate?: T;
  endDate?: T;
  nameOverride?: T;
  location?: T;
  url?: T;
  registrationOpensAt?: T;
  registrationClosesAt?: T;
  registrationUrl?: T;
  registrationType?: T;
  registrationStatusOverride?: T;
  sourceUrl?: T;
  verifiedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "race-records_select".
 */
export interface RaceRecordsSelect<T extends boolean = true> {
  owner?: T;
  eventId?: T;
  distanceId?: T;
  year?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "race-schedule_select".
 */
export interface RaceScheduleSelect<T extends boolean = true> {
  name?: T;
  nameZh?: T;
  series?: T;
  startDate?: T;
  endDate?: T;
  eventId?: T;
  country?: T;
  location?: T;
  distanceSummary?: T;
  url?: T;
  registrationOpensAt?: T;
  registrationClosesAt?: T;
  registrationUrl?: T;
  registrationType?: T;
  registrationStatusOverride?: T;
  sourceUrl?: T;
  verifiedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  heroTitleEn?: string | null;
  heroTitleZh?: string | null;
  metadata?: {
    titleDefault?: string | null;
    titleTemplate?: string | null;
    description?: string | null;
  };
  social?: {
    github?: string | null;
  };
  topNavItems?:
    | {
        label: string;
        href: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  heroTitleEn?: T;
  heroTitleZh?: T;
  metadata?:
    | T
    | {
        titleDefault?: T;
        titleTemplate?: T;
        description?: T;
      };
  social?:
    | T
    | {
        github?: T;
      };
  topNavItems?:
    | T
    | {
        label?: T;
        href?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}